### ISSUE TITLE
Add discard button

### ISSUE THREAD

**Issue by TueeNguyen** [TueeNguyen/SplitWise3#7]
We need a way to reset the forms to its initial value. 

We can add a button in the bottom of the page that says `Reset` and let's add [a reset icon](https://mui.com/material-ui/material-icons/?query=reset&selected=RestartAlt) to the button. 

Rough draft: 
![image](https://user-images.githubusercontent.com/58532267/170171064-004a08d2-3ba9-4e0d-8e92-5c8f80f70087.png)

The button can be added here after `FieldArray` and the `onClick` function will just [`setValues`](https://formik.org/docs/api/formik#setvalues-fields-reactsetstateaction-field-string-any--shouldvalidate-boolean--void) of the forms to `initialValues`
https://github.com/TueeNguyen/SplitWise3/blob/29d6122cda7c75126058e614ed3760e83ecac066/src/web/src/components/expenses/Expense.js#L57-L59

**Comment by hayatdurgut** [comment]
Hi I want to work on this issue. Please assign me.

**Comment by hayatdurgut** [comment]
I have homework, I will be glad if you come back :)

**Comment by TueeNguyen** [comment]
Hi, sure you can take it

**Comment by TueeNguyen** [comment]
I will update more on this issue

**Comment by TueeNguyen** [comment]
@hayatdurgut Please ping me here or on discord https://discord.gg/fz7RtW3AVM

**Comment by hayatdurgut** [comment]
thank you

**Comment by hayatdurgut** [comment]
thank you i joined

**Comment by hayatdurgut** [comment]
Thank you I joined
